version: "3"
services:
  app:
    container_name: express-mongo
    restart: always
    build: ./
    ports:
      - "2000:3000"
    volumes:
      - .:/app
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  mongo:
    image: mongo:latest
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
